/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "stdcycles.h"

shader node_diffuse_bsdf(color Color = 0.8,
                         float Roughness = 0.0,
                         string distribution = "diffuse",
                         normal Normal = N,
                         output closure color BSDF = 0)
{
  if (distribution == "burley")
    BSDF = Color * burley_diffuse_bsdf(Normal, clamp(Color, 0.0, 1.0), Roughness);
  else if (distribution == "oren_nayar" || Roughness >= 1e-5)
    BSDF = oren_nayar_diffuse_bsdf(Normal, clamp(Color, 0.0, 1.0), Roughness);
  else
    BSDF = Color * diffuse(Normal);
}
